name: Cache Demo Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-example:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Cache step with email-like name
      - name: prime-cache-654b927        # <-- This is the step name shown in UI
        id: prime_cache                  # <-- ID needed to reference outputs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-654b927
          restore-keys: |
            cache-654b927

      # Step 4: Echo cache hit/miss
      - name: Echo cache result
        run: |
          if [ "${{ steps.prime_cache.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          pip install requests
